---
- name: Grasp minikube package
  shell: |
    curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-darwin-amd64
- name: Install minikube
  shell: |
    install minikube-darwin-amd64 /usr/local/bin/minikube

- name: Start minikube
  shell: |
    minikube start
