---
- name: Grasp minikube package
  shell: |
    curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
- name: Install minikube
  shell: |
    install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64

- name: Set minikube driver to docker
  shell: |
    minikube config set driver docker
- name: Start minikube
  shell: |
    minikube start

- name: download kubectl
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

- name: install kubectl
  shell: |
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl