#!/bin/bash
set -x

echo "======= add related folders ======="
mkdir -p /data/XXXXX/images/uploaded
mkdir -p /data/XXXXX/images/camera
mkdir -p /data/XXXXX/images/captioned
mkdir -p /data/XXXXX/images/detected
mkdir -p /data/XXXXX/images/meters/uploaded
mkdir -p /data/XXXXX/videos/camera
mkdir -p /data/XXXXX/videos/uploaded
mkdir -p /data/XXXXX/videos/captioned
mkdir -p /data/XXXXX/videos/searched
mkdir -p /data/XXXXX/models
mkdir -p /preserve/logs



echo "======= create label file ======="
lshw -c network | grep serial | head -n 1 | awk '{ print $2 }' > /tmp/SN
base64 /tmp/SN > /etc/loopback.conf
sed -i 's/^/'$(($RANDOM%10))'/' /etc/loopback.conf


echo "======== change nginx config ====="
get_hostname=$(hostname)
sed -i s/"nginx!"/$get_hostname/g /usr/share/nginx/html/index.html


echo "======== enable systemd service ======"
systemctl daemon-reload
systemctl restart nginx
systemctl enable nginx


