#!/bin/bash
set -e
case "$1" in
        install)
        #create user and group when first time installation
        getent group nginxdemo >/dev/null || groupadd -g 1007 -r nginxdemo
        getent passwd nginxdemo >/dev/null || \
        useradd -r -u 1007 -g nginxdemo -s /sbin/nologin \
        -d /tmp -c "nginxdemo" nginxdemo
        echo 'nginxdemo ALL=(ALL) NOPASSWD:/bin/systemctl start nginx,/bin/systemctl stop nginx,/bin/systemctl restart nginx' > /etc/sudoers.d/nginxdemo
        echo 'nginxdemo ALL=(ALL) NOPASSWD:/usr/bin/apt-get remove,/usr/bin/dpkg' >> /etc/sudoers.d/nginxdemo
        ;;
        update|abort-upgrade)
        echo "just update"
        ;;
esac
exit 0