apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mysql-service.fullname" . }}
  labels:
    {{- include "mysql-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mysql-service.selectorLabels" . | nindent 6 }}
      #serviceName: "mysql"
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        {{- include "mysql-service.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3306
          name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: root-password

        volumeMounts:
          - name: mysql-initdb
            mountPath: /docker-entrypoint-initdb.d
          - name: mysql-initdb
            mountPath: /etc/mysql/my.cnf
            subPath: my.cnf
          - name: mysql-data
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
            items:
              - key: initdb.sql
                path: initdb.sql
              - key: my.cnf
                path: my.cnf
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi